name: Test Pipeline

on:
  workflow_dispatch:

jobs:
  sample:
    name: Run sample
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - run: npm install
